### ISSUE TITLE
[feature] Provide a customization option for the clangd command line

### ISSUE THREAD

**Issue by jefftrull** [emacs-lsp/lsp-clangd#12] opened 2018-08-16 22:57 UTC
I've found that in order for clangd to find my (out of source built) `compile_commands.json` I need to also supply a special command line option to clangd: `--compile-commands-dir=`.

Can a customization option be provided that allows this?

**Comment by tee3** [comment] 2018-08-16 23:53
This sounds reasonable and straightforward to achieve.  I will look into doing it sometime soon.

**Comment by tee3** [comment] 2018-11-28 07:12
It looks like `lsp-mode` is going to subsume all the individual language server modes described in https://github.com/emacs-lsp/lsp-mode/issues/479. I'll be closing this issue once that happens.

**Comment by tee3** [comment] 2018-11-28 07:12
It looks like `lsp-mode` is going to subsume all the individual language server modes described in https://github.com/emacs-lsp/lsp-mode/issues/479. I'll be closing this issue once that happens.

**Comment by yyoncho** [comment] 2018-11-28 18:56
@tee3 just want to mention that lsp-mode will host only the simple language server adapters(clangd is one of them). The more complex like ccls and jdt ls will still be in separate packages.

**Comment by tee3** [comment] 2018-12-09 14:31
This is now (hopefully) implemented in the latest `lsp-mode` `lsp.el`.  Please try it out and file an issue at `lsp-mode` if the problem is not resolved.  Thanks!

**Closed** 2019-01-10 18:09 UTC
